steps:

# checkout submodules (not sure how, so clone instead)
- name: gcr.io/cloud-builders/wget
  args: ['-O', 'api-common-protos.tar.gz', 'https://github.com/googleapis/api-common-protos/archive/c77d050e310b5f94f3f4abcb7f28ab5a008361d5.tar.gz']
  dir: 'generator/api-common-protos'
- name: ubuntu
  args: ['tar', 'xvf', 'api-common-protos.tar.gz', '--strip-components=1']
  dir: 'generator/api-common-protos'
 
# build generator  
- id: build_generator
  name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: 'generator'
- id: dockerize_generator
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kotlin-gapic/kgen:$COMMIT_SHA', '-t', 'gcr.io/kotlin-gapic/kgen:latest', '.']
  dir: 'generator'

# build examples
- id: example_key
  name: 'ubuntu'
  args: ['bash', '-c', 'touch app/src/main/res/raw/sa.json']
  dir: 'example-api-clients'
  waitFor: ['-']
- id: build_examples
  name: 'gcr.io/kotlin-gapic/example-builder'
  args: []
  dir: 'examples'
  waitFor:
    - build_generator
    - example_key

# TODO:
# run example tests
# - id: examples_tester
#   name: 'gcr.io/cloud-builders/gcloud'
#   args: ["firebase", "test", "android", "run", "--app", "app/build/outputs/apk/debug/app-debug.apk", "--test", "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"]
#   dir: 'examples'
#   waitFor:
#     - build_examples

# spin up showcase server and run tests
- id: start_showcase
  name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  dir: 'showcase-test'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: 'showcase-test'
  env:
  - 'HOST=showcase'
  - 'PORT=7469'
  waitFor: 
    - start_showcase
    - build_generator

images: 
- 'gcr.io/kotlin-gapic/kgen:$COMMIT_SHA'
- 'gcr.io/kotlin-gapic/kgen:latest'

timeout: 1200s
