// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/example/hello.proto

package google.example;

public final class Hello {
  private Hello() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
