// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/example/hello.proto

package google.example;

public interface HiRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.example.HiRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /** <code>optional string query = 1;</code> */
  java.lang.String getQuery();
  /** <code>optional string query = 1;</code> */
  com.google.protobuf.ByteString getQueryBytes();
}
