// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/example/hello.proto

package google.example;

/** Protobuf type {@code google.example.HiRequest} */
public final class HiRequest
    extends com.google.protobuf.GeneratedMessageLite<HiRequest, HiRequest.Builder>
    implements
    // @@protoc_insertion_point(message_implements:google.example.HiRequest)
    HiRequestOrBuilder {
  private HiRequest() {
    query_ = "";
  }

  public static final int QUERY_FIELD_NUMBER = 1;
  private java.lang.String query_;
  /** <code>optional string query = 1;</code> */
  public java.lang.String getQuery() {
    return query_;
  }
  /** <code>optional string query = 1;</code> */
  public com.google.protobuf.ByteString getQueryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(query_);
  }
  /** <code>optional string query = 1;</code> */
  private void setQuery(java.lang.String value) {
    if (value == null) {
      throw new NullPointerException();
    }

    query_ = value;
  }
  /** <code>optional string query = 1;</code> */
  private void clearQuery() {

    query_ = getDefaultInstance().getQuery();
  }
  /** <code>optional string query = 1;</code> */
  private void setQueryBytes(com.google.protobuf.ByteString value) {
    if (value == null) {
      throw new NullPointerException();
    }
    checkByteStringIsUtf8(value);

    query_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!query_.isEmpty()) {
      output.writeString(1, getQuery());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!query_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream.computeStringSize(1, getQuery());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static google.example.HiRequest parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static google.example.HiRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static google.example.HiRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static google.example.HiRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static google.example.HiRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static google.example.HiRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static google.example.HiRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static google.example.HiRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static google.example.HiRequest parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static google.example.HiRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(google.example.HiRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /** Protobuf type {@code google.example.HiRequest} */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<google.example.HiRequest, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.example.HiRequest)
      google.example.HiRequestOrBuilder {
    // Construct using google.example.HiRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /** <code>optional string query = 1;</code> */
    public java.lang.String getQuery() {
      return instance.getQuery();
    }
    /** <code>optional string query = 1;</code> */
    public com.google.protobuf.ByteString getQueryBytes() {
      return instance.getQueryBytes();
    }
    /** <code>optional string query = 1;</code> */
    public Builder setQuery(java.lang.String value) {
      copyOnWrite();
      instance.setQuery(value);
      return this;
    }
    /** <code>optional string query = 1;</code> */
    public Builder clearQuery() {
      copyOnWrite();
      instance.clearQuery();
      return this;
    }
    /** <code>optional string query = 1;</code> */
    public Builder setQueryBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setQueryBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.example.HiRequest)
  }

  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new google.example.HiRequest();
        }
      case IS_INITIALIZED:
        {
          return DEFAULT_INSTANCE;
        }
      case MAKE_IMMUTABLE:
        {
          return null;
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case VISIT:
        {
          Visitor visitor = (Visitor) arg0;
          google.example.HiRequest other = (google.example.HiRequest) arg1;
          query_ =
              visitor.visitString(!query_.isEmpty(), query_, !other.query_.isEmpty(), other.query_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor.INSTANCE) {}
          return this;
        }
      case MERGE_FROM_STREAM:
        {
          com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default:
                  {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                case 10:
                  {
                    String s = input.readStringRequireUtf8();

                    query_ = s;
                    break;
                  }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                    .setUnfinishedMessage(this));
          } finally {
          }
        }
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          if (PARSER == null) {
            synchronized (google.example.HiRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:google.example.HiRequest)
  private static final google.example.HiRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new HiRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static google.example.HiRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HiRequest> PARSER;

  public static com.google.protobuf.Parser<HiRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
