// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/example/hello.proto

package google.example;

public interface HiResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.example.HiResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /** <code>optional string result = 1;</code> */
  java.lang.String getResult();
  /** <code>optional string result = 1;</code> */
  com.google.protobuf.ByteString getResultBytes();
}
